FROM gitea/gitea:1.5.2

ENV \
    GITEA_ADMIN_USER=ScottLogic \
    GITEA_ADMIN_PASSWORD=5lgitHack \
    GITEA_ADMIN_EMAIL=hackathon@scottlogic.co.uk

ADD conf /conf
ADD scripts/gitea-entrypoint.sh /entrypoint
RUN apk --no-cache add dos2unix \
    && dos2unix /entrypoint \
    && chmod +x /entrypoint

ENTRYPOINT ["/entrypoint"]
