makeMovesTimeoutSeconds=5
maxPhases=512
maxVisibleDistance=6
collectablesSpawnFrequency=0.2
battleRadius=2
maxCollectablesSpawnedPerPhase=4
minCollectableDistanceFromSpawn=8
spawnPhases=8
initialiseTimeoutSeconds=30