makeMovesTimeoutMillis=500
maxPhases=512
maxVisibleDistance=6
perTurnFoodSpawnProbability=0.8
battleRadius=2
maxCollectablesSpawnedPerPhase=4
minCollectableDistanceFromSpawn=8
spawnPhases=8
initialiseTimeoutMillis=2000
