# makeMovesTimeoutMillis=
# maxPhases=
# maxVisibleDistance=
# perTurnFoodSpawnProbability=
# battleRadius=
# maxCollectablesSpawnedPerPhase=
# minCollectableDistanceFromSpawn=
# spawnPhases=
# initialiseTimeoutMillis=
