const CUTOFFCONDITION = {
    RANK_STABLE: 'RANK_STABLE',
    TURN_LIMIT_REACHED: 'TURN_LIMIT_REACHED',
    LONE_SURVIVOR: 'LONE_SURVIVOR',
    NOT_GATHERING: 'NOT_GATHERING',
    NOT_RAZING: 'NOT_RAZING'
};

module.exports = CUTOFFCONDITION;
